name: AutoPost Blogger

on:
  workflow_dispatch: # Untuk trigger manual
  schedule:
    - cron: '2 3 * * *' # 💡 Ganti jam sesuai test UTC (misal 2 menit dari sekarang = 03:02 UTC)
    - cron: '0 17 * * *' # Jam 17:00 UTC (00:00 WIB)
    - cron: '0 18 * * *' # Jam 18:00 UTC (01:00 WIB)
    - cron: '0 19 * * *' # Jam 19:00 UTC (02:00 WIB - waktu yang Anda mau)

jobs:
  autopost:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run autopost script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          ULTRAMSG_INSTANCE: ${{ secrets.ULTRAMSG_INSTANCE }}
          ULTRAMSG_TOKEN: ${{ secrets.ULTRAMSG_TOKEN }}
          WA_PHONE: ${{ secrets.WA_PHONE }}
        run: |
          echo "🕒 Job started at $(TZ='Asia/Jakarta' date)"
          node post.js
          echo "✅ Job completed at $(TZ='Asia/Jakarta' date)"

      - name: Upload report
        uses: actions/upload-artifact@v4 # 🔄 Versi diperbaiki
        if: always()
        with:
          name: blogger-reports
          path: |
            report_*.json
            failed_posts.json
