name: Post to Blogger

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours to avoid overlap with rate-limited posts

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set a timeout to prevent hung jobs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '18'  # Consistent with your choice
          cache: 'npm'  # Cache node_modules for faster runs

      - name: Install dependencies
        run: npm install googleapis axios date-fns-tz bottleneck

      - name: Run Blogger Post Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          ULTRAMSG_INSTANCE: ${{ secrets.ULTRAMSG_INSTANCE }}
          ULTRAMSG_TOKEN: ${{ secrets.ULTRAMSG_TOKEN }}
          WA_PHONE: ${{ secrets.WA_PHONE }}
        run: node post.js  # Corrected file name
