name: Post to Blogger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Blogger Post Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          ULTRAMSG_INSTANCE: ${{ secrets.ULTRAMSG_INSTANCE }}
          ULTRAMSG_TOKEN: ${{ secrets.ULTRAMSG_TOKEN }}
          WA_PHONE: ${{ secrets.WA_PHONE }}
        run: node post.js
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            *.json
            *.log
